QCoDeS/Qcodes_contrib_drivers

qcodes_contrib_drivers/drivers/Keysight/Keysight_E8267D.py, qcodes_contrib_drivers/drivers/QuTech/IVVI.py
1) This PR ports the updates of Keysight E8267D driver from Qcodes/qcodes repository to this repository.
2) This also copies the updates from the `update_ivvi_copy` branch from @jenshnielsen. 
3) Tag v0.2.0 created. 
@jenshnielsen
=> Port updates of Keysight E8267D  + copy updates from  `update_ivvi_copy`  branch 

qcodes_contrib_drivers/tests/test_Spectrum_M4i.py
Add simple tests for M4i driver.  (should have been part of #24)
@astafan8
=> Add unit tests for Spectrum M4i

qcodes_contrib_drivers/drivers/Tektronix/AFG3000.py
Qcodes driver for Tektronix AFG3000 series arbitrary function generators
=> Add AFG3000

qcodes_contrib_drivers/drivers/Keysight/Keysight_E36313A.py
new pull request, 
old pull request [here](https://github.com/QCoDeS/Qcodes_contrib_drivers/pull/46) 
all comments from the old pull request will be considered in the new one
=> Keysight E36313A power source

docs/examples/Vaunix_LDA.ipynb, qcodes_contrib_drivers/drivers/Vaunix/LDA.py
This PR contains a driver for Vaunix LDA digital attenuators.
=> Vaunix LDA step attenuator

qcodes_contrib_drivers/drivers/Spectrum/pyspcm.py
=> use logging framework to print information about M4i driver loading

docs/examples/Thorlabs_K10CR1.ipynb, qcodes_contrib_drivers/drivers/Thorlabs/APT.py, qcodes_contrib_drivers/drivers/Thorlabs/K10CR1.py, qcodes_contrib_drivers/drivers/Thorlabs/MFF10x.py, qcodes_contrib_drivers/drivers/Thorlabs/PRM1Z8.py
* Added a driver for Thorlabs K10CR1 rotator
* Extended the APT.dll-wrapper "Thorlabs_APT" with more functionality
* Minor changes to Thorlabs PRM1Z8 and MFF10x
=> Thorlabs K10CR1 driver

qcodes_contrib_drivers/drivers/NationalInstruments/Switch.py
Fix NI Switch driver session not being closed properly
=> Fix close method of NI Switch driver

qcodes_contrib_drivers/drivers/Vaunix/LDA.py
Improved error handling in LDA initialization and close, and add set_parser for the attenuation parameter.
=> Small fixes to Vaunix LDA driver

docs/conf.py
Updating docs config file with addition of ('py:class', 'spirack.SPI_rack') in nitpick_ignore list.
@WilliamHPNielsen
=> Update docs config file

qcodes_contrib_drivers/drivers/SingleQuantum/SingleQuantum.py
This PR adds the qcodes driver for SingleQuantum.
The code has some wrappers to communicate using JSON.
Any tips or comments are appreciated :)
=> adds the SingleQuantum driver

docs/conf.py, qcodes_contrib_drivers/drivers/NationalInstruments/PXIe_2597.py, qcodes_contrib_drivers/drivers/NationalInstruments/RFSG.py, qcodes_contrib_drivers/drivers/NationalInstruments/Switch.py, qcodes_contrib_drivers/drivers/NationalInstruments/dll_wrapper.py
Fixes issue #61 
Add empty __init__.py file for NationalInstruments folder
@WilliamHPNielsen
=> Add init file for NationalInstruments

docs/examples/Rohde_Schwarz_HMP4040.ipynb, qcodes_contrib_drivers/drivers/RohdeSchwarz/HMP2020.py, qcodes_contrib_drivers/drivers/RohdeSchwarz/HMP2030.py, qcodes_contrib_drivers/drivers/RohdeSchwarz/HMP4030.py, qcodes_contrib_drivers/drivers/RohdeSchwarz/HMP4040.py, qcodes_contrib_drivers/drivers/RohdeSchwarz/private/HMP.py
Driver for the R&S HMP series (similar to driver for HMC series, but with some subtle differences)
=> Feature/Rohde&Schwarz HMP series

docs/examples/BlueFors.ipynb, qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
This driver allow the readout of basic information, pressures and temperature, for BlueFors fridges.
=> Driver for BlueFors fridges

docs/examples/SingleQuantum.ipynb
Adds a notebook example for the SQ driver
=> Example single quantum

docs/conf.py, qcodes_contrib_drivers/drivers/AimTTi/EL320P.py, qcodes_contrib_drivers/drivers/Attocube/ANC300.py, qcodes_contrib_drivers/drivers/Cryogenic/CryogenicSMS120C.py, qcodes_contrib_drivers/drivers/Oxford/ILM200.py, qcodes_contrib_drivers/drivers/Oxford/IPS120.py, qcodes_contrib_drivers/drivers/Oxford/kelvinox.py, qcodes_contrib_drivers/drivers/QuTech/IVVI.py, qcodes_contrib_drivers/drivers/RohdeSchwarz/SMW200Asim.py
Replace deprecated `visa` import with `pyvisa` 
Update link to numpy intersphinx that has moved
=> CI cleanup

qcodes_contrib_drivers/tests/test_Keysight_M3201A.py
These tests were not correctly moved along with the driver
=> port keysight m3201 driver tests from qcodes

qcodes_contrib_drivers/drivers/Keysight/SD_common/SD_AWG_Async.py
Fixed memory initialization. It was broken in review process.
BTW. Thanks for review of #55 and adding the parameter typing.
=> Keysight m3202a - Fix

docs/examples/ITest.ipynb, qcodes_contrib_drivers/drivers/Bilt/ITest.py
Allow set and get of voltage with different ramps.
=> Driver for ITest from Bilt

docs/examples/CopperMountain_M5180.ipynb, qcodes_contrib_drivers/drivers/CopperMountain/M5180.py
This PR adds a driver and an example for the M5180 VNA from CopperMountain.
=> add driver for CopperMountain VNA M5180 with example

LICENSE_TEKTRONIX_AWG520_KEITHLEY_2700, readme.rst, setup.cfg
* Add notice about license to readme
* add gpl classifier
* add license file for gpl 2
* add license files to sdist and bdist_wheel
fixes #92
=> Clarify license

docs/conf.py
=> fixed pyvisa intersphinx link

qcodes_contrib_drivers/drivers/GeneralMicrowave/GM349.py, qcodes_contrib_drivers/drivers/Holzworth/HS9008B.py, qcodes_contrib_drivers/drivers/NationalInstruments/DAQ.py
Slightly modified Holzworth HS900 driver so that it now works properly for Holzworth HS9008B signal generators. Modified National Instrument DAQ driver so that digital output devices can now be properly controlled. Tested with NI PXI-6509.
=> Add Holzworth HS9008B, General Microwave GM349, and NI DAQ drivers

.github/workflows/docs.yaml
As we are no longer testing 3.7
=> upload docs from 3.10

.github/workflows/docs.yaml, .github/workflows/pytest.yaml
on new push to the same branch / pr
=> cancel old github actions jobs

qcodes_contrib_drivers/drivers/DaylightSolutions/MIRcat.py
Add driver for the DRS Daylight Solutions MIRcat QCL infrared laser.
=> DaylightSolutions MIRcat

pyproject.toml, src/qcodes_contrib_drivers/drivers/Attocube/AMC100.py
This PR adds a driver for the Attocube AMC100 controller.
=> Attocube AMC100 driver

src/qcodes_contrib_drivers/drivers/Keysight/SD_common/SD_AWG_Async.py, src/qcodes_contrib_drivers/drivers/Keysight/SD_common/SD_Module.py, src/qcodes_contrib_drivers/drivers/Keysight/SD_common/memory_manager.py
Added get_idn(), get_temperature(), release_waveform_memory()
=> Keysight get idn and more

src/qcodes_contrib_drivers/drivers/QuTech/D4.py, src/qcodes_contrib_drivers/drivers/QuTech/D5a.py, src/qcodes_contrib_drivers/drivers/QuTech/F1d.py, src/qcodes_contrib_drivers/drivers/QuTech/M2j.py, src/qcodes_contrib_drivers/drivers/QuTech/S5i.py
get_idn was missing in these instruments. This resulted in many warnings in the logging.
=> Added get_idn() to QuTech Instruments.

.github/workflows/docs.yaml, .github/workflows/pytest.yaml, pyproject.toml
In line with QCoDeS and [spec-0](https://scientific-python.org/specs/spec-0000/)
=> Drop python 3.9 support

docs/examples/Rigol_DSG3136B.ipynb, src/qcodes_contrib_drivers/drivers/Rigol/Rigol_DSG3136B.py
Added documentation, in response to https://github.com/QCoDeS/Qcodes_contrib_drivers/pull/197#discussion_r1083879979
=> Added an example notebook for the Rigol DSG3136B driver.

docs/conf.py, pyproject.toml
Matches Qcodes and will hopefully help resolve docs build errors in other prs (since we then can upgrade docutils and sphinx)
=> Switch to furo theme

docs/examples/Cryomagnetics/Model_4G.ipynb, docs/examples/index.rst, src/qcodes_contrib_drivers/drivers/Cryomagnetics/Model_4G.py
@astafan8 and @jenshnielsen please have a look.
=> add cryomagnetics driver and examples for model 4G magnet power supply
