QCoDeS/Qcodes_contrib_drivers

- qcodes_contrib_drivers/drivers/Spectrum/M4i.py
The previous implementation would block the python session for the entire duration of the acquisition of the M4i. This new implementation allows the user to override the `wait_ready` command (either in a subclass or by dynamic update of the class method), so that the python session is not blocked.
@astafan8 
For example to make plots interactive during data acquisition we use the following method
```
def m4i_wait_ready(self, timeout_step: Optional[float] = None) -> int:
"""  Wait for the M4i card to be ready 
Args:
timeout_step (None or float): If None then wait in blocking mode. Otherwise wait for the result in steps of specified duration (in miliseconds)
If the timeout_step is None, then wait for the card to be ready in blocking mode. Otherwise
wait steps of the specified duration …
```
> refactor M4i to have a wait ready method

- qcodes_contrib_drivers/drivers/StanfordResearchSystems/SIM928.py
... because it's a private method, and, moreover, will be deprecated in qcodes at some point.
@antsr @WilliamHPNielsen is this legit?
> Stanford Research SIM928: Refactor set_voltage to avoid use of _save_val

- docs/examples/Attocube_ANC300.ipynb
- qcodes_contrib_drivers/drivers/Attocube/ANC300.py
- qcodes_contrib_drivers/drivers/Attocube/ANC300sim.py
The test device has the ANC300 controller and two ANM150 axis
modules. Therefore no automatic test for other modules is
included in the driver (no tests possible).
The communication is done via PySerial. The ANC300sim.py is
included to simulate the correct answers from the device.
Activate the simulation with a flag in the ANC300.py file.
> feat: driver for Attocube ANC300

- docs/conf.py
As qcodes docs are no longer build with nitpicky.
Fixes https://github.com/QCoDeS/Qcodes_contrib_drivers/issues/70
> Dont build contrib driver docs with nitpick

- qcodes_contrib_drivers/drivers/Newport/AG_UC8.py
@farbo this should get the ci to pass with the newest qcodes version
> fix type checking with qcodes 019 and pyvisa 1.11

- qcodes_contrib_drivers/drivers/Keysight/Keysight_E8267D.py
Currently there is a driver for Keysight E8267C in Qcodes repository which has 4 parameters similar to Keysight E8267D driver but their names differ. This PR makes them consistent. 
- Updates param names in Keysight E8267D with same names as that of similar parameters in Keysight E8267C and deprecates old ones
@jenshnielsen @astafan8
> Update param names in Keysight E8267D similar to ones in qcodes driver Keysight E8267C

- qcodes_contrib_drivers/drivers/Bilt/ITest.py
This PR fixes an error in the get function of the state parameter and changes default value of synchronous_delay parameter and delete trailing white spaces.
Previously while getting  the state parameter of a channel (15 for example) by `dac.channels[15].state()`, the following error was raised:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Miniconda3\lib\site-packages\qcodes\instrument\parameter.py in _from_raw_value_to_value(self, raw_value)
563                 try:
--> 564                     value = self.inverse_val_mapping[int(value)]
565                 except (ValueError, KeyError):
KeyError: 0
During handling of the above exception, another exception occurred:
KeyError …
```
> ITest: fix get function of state parameter

- qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
This PR fixes an error in reading the log file that could occur if the log file is blocked by another program. This generally arises if the log files are periodically synchronized e.g. with DSynchronize (http://dimio.altervista.org/eng/#DSynchronize).
If the file is not readable at the time of getting the parameter, not a number (nan) is returned.
It fixes the following error:
```
2021-05-25 18:29:24,840 ¦ qcodes.dataset.measurements ¦ WARNING ¦ measurements ¦ __exit__ ¦ 584 ¦ An exception occured in measurement with guid: aaaaaaaa-0000-0000-0000-0179a44ffb4b;
Traceback:
Traceback (most recent call last):
File "<ipython-input-26-13ac4aa9f5da>", line 14, in <module>
(bluelagoon.temperature_mixing_chamber, bluelagoon.temperature_mixing_chamber()),
File …
```
> Fix bluefors driver permission error

- qcodes_contrib_drivers/drivers/Vaunix/LDA.py
This PR adds labels like "ch1 Attenuation" instead of just "Attenuation" when doing attenuation sweeps with a Vaunix LDA with multiple channels.
> Add channel name to labels in Vaunix LDA

- docs/examples/Holzworth_HS900.ipynb
- qcodes_contrib_drivers/drivers/Holzworth/HS900.py
This PR adds a driver and an example notebook for the RF synthesizer from Holzworth. It has been tested for the model HS9002B, but according to the manual, it should work for other models too. The driver has mainly been written by Valentin John.
> Feat add holzworth driver

- qcodes_contrib_drivers/drivers/CopperMountain/M5180.py
This PR includes some minor improvements of the Coppermountain M5180 driver and it passes kwargs to its baseclass as required by qcodes.
@FarBo could you please review it? Thanks.
> Feat improvements m5180 driver

- qcodes_contrib_drivers/drivers/ZurichInstruments/ZIHDAWG8.py
The `.wave` format is more efficient than the `.csv` format.
@astafan8
> add writing to .wave format for the HDAWG8 driver

- docs/examples/SignalCore.ipynb
- qcodes_contrib_drivers/drivers/SignalCore/SignalCore.py
> Add SignalCore driver

- qcodes_contrib_drivers/drivers/Tektronix/AFG3000.py
Temp fix for https://github.com/QCoDeS/Qcodes_contrib_drivers/issues/115
May pass incorrect min/max values.
> AFG3000: use PermissiveMultiples until MultiType can AND

- qcodes_contrib_drivers/drivers/Tektronix/AFG3000.py
This would have caught the incorrect validator usage from https://github.com/QCoDeS/Qcodes_contrib_drivers/issues/115
Also rewrite the driver to use the log attached to the instrument already
> Add typing to afg3000 driver

- qcodes_contrib_drivers/drivers/QDevil/QDAC2.py
@jpsecher 
* Python files are only packaged if you include a `__init__.py` file in the folder not a `__init_.py` file 
* Do you want the yaml files to be part of the package or Are they only indended to be there for running tests from source.
If you want to include the files then then should be included as pacakge data in setup.cfg
Compare https://github.com/QCoDeS/Qcodes_contrib_drivers/blob/master/setup.cfg to 
https://github.com/QCoDeS/Qcodes/blob/master/setup.cfg#L55
> QDevil: Correct typo in init file

- docs/examples/NationalInstruments_RFSG.ipynb
- qcodes_contrib_drivers/drivers/NationalInstruments/RFSG.py
Add functionality to enable analog (amplitude / frequency / phase) modulation for NI-RFSG based devices. Includes example code in the example notebook. Tested amplitude modulation with a PXIe-5654.
> Analog modulation for NI RFSG driver

- qcodes_contrib_drivers/drivers/Tektronix/AFG3000.py
Before this change, setting boolean parameters to `True`/`False` failed silently:
```python
from qcodes_contrib_drivers.drivers.Tektronix.AFG3000 import AFG3000
afg = AFG3000("AFG", address=...)
afg.state_output1.set(1)
assert afg.state_output1() is True  # ok
afg.state_output1.set(False)  # no error
assert afg.state_output1() is False  # fails, afg.state_output1 is still True !
afg.state_output1.set(0)
assert afg.state_output1() is False
```
With this patch, the second assert above also succeeds.
Note: while this is a bug in this driver, interestingly `Enum(0, 1).validate(True)` succeeds (works also with floats 0.0 and 1.0). Seems like this is due to `hash(1) == hash(1.0) == hash(True) == 1`. Perhaps this is a bit surprising, I would expect `Enum` to be a bit more strict. But maybe it's …
> AFG3000: Use on_off_val_mapping instead of custom vals and get_parser

- qcodes_contrib_drivers/drivers/ERAInstruments/erasynth.py
`ERASynthPlusPlus` inheritance from `EraSynthPlus` was causing the duplicated addition of certain parameters, resulting in the imposibility to instantiate an `ERASynthPlusPlus` object.
- Change `ERASynthPlusPlus` inheritance from `ERASynthPlus` to `ERASynthBase`.
- Add the missing parameters that were only created in `ERASynthPlus` to `ERASynthPlusPlus`.
> Fix: EraSynth++ duplicated parameters error

- pyproject.toml
- qcodes_contrib_drivers/tests/test_Keysight_M3201A.py
This means that mypy will only skip missing imports for modules that we have explicitly marked as known to be missing or non typed. This also found a bug in a test file. These tests dont run automatically since they require the instrument being present
> Mypy better missing imports

- .github/workflows/docs.yaml
- .github/workflows/pytest.yaml
- .github/workflows/upload_to_pypi.yaml
- qcodes_contrib_drivers/drivers/SignalCore/SignalCore.py
- setup.cfg
Now that QCoDeS has dropped support for 3.7 lets drop it here too
> Drop python 3.7

- qcodes_contrib_drivers/drivers/Tektronix/AFG3000.py
- setup.cfg
Apply https://github.com/QCoDeS/Qcodes/pull/3917 closes #115
> Tektronix/AFG3000: use MultiType with combiner argument

- pyproject.toml
- setup.cfg
- setup.py
Mirrors what is done in qcodes.
> move pep621 standard config to pyproject.toml

- qcodes_contrib_drivers/drivers/Tektronix/Keithley_6500.py
The `Keithley_Sense` submodule defined the `label` and `unit` of the `measure` parameter incorrect. We have to set them as a string, not as a method.
> Fix Keithley6500 driver

- qcodes_contrib_drivers/drivers/Bilt/ITest.py
- requirements.txt
and use ~= for requirements
I do not know why dependabot is not triggering this
> upgrade mypy to 1.0.0

- qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
Within get_temperature( ), change the format in pd.to_datetime( ). Because there is no space before the day with BlueFors Control Software v2.2.
> BlueFors: update datetime parsing to be compatibe with v2.2 bluefors software

- .github/workflows/upload_to_pypi.yaml
using the trusted flow at https://docs.pypi.org/trusted-publishers/
> Switch publish to official pypi action

- qcodes_contrib_drivers/drivers/StanfordResearchSystems/CS580.py
Add support for SRS CS580 current source
> Stanford Research Systems CS580

- qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
This PR adds the functionality to read old or new log file versions. The code comes from here: https://github.com/pyplotter/pyplotter/commit/eae409e98156bec1a7255acf19050d0af6d0486d Thanks @edumur 
Please have a look @astafan8 and @ptar543
> BlueFors: make driver compatible with old and new log files

- qcodes_contrib_drivers/drivers/CopperMountain/M5180.py
As the title of this PR says, it adds parameters for single IQ measurements at a fixed frequency, similar to PointMagPhase parameters. It also fixes a function that checks for properly set sweep settings.
> add parameters for a single iq measurements (PointIQ)

- qcodes_contrib_drivers/drivers/Bilt/ITest.py
- initializing the DAC is not changing any outputs by default (there is a flag to reset it to 0V and 12 range)
- ramping is now by default in exponential mode to be consistent with the idea of ramping qcodes parameters (step, inter_delay, post_delay)
- implementation of autorange parameter
- global zeroing and printing functions
> improvements of the ITest driver including:

- qcodes_contrib_drivers/drivers/QDevil/QDAC2.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_array.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_awg.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_current.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_sine.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_source_list.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_source_sweep.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_square.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_triangle.py
- qcodes_contrib_drivers/tests/QDevil/test_sim_qdac2_virtual_gates.py
- Additional init is not needed anymore
> QDAC2: start_once_on triggers

- qcodes_contrib_drivers/drivers/DaylightSolutions/MIRcat.py
The new update reads the parameters from the QCL chips to set up the appropriate limits on wavelength and current range.
> DaylightSolutions MIRCat driver - different QCL chips

- pyproject.toml
- qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
Blueforce drivers depends on pandas but this was never added as a dependency.
Add pandas and pandas stubs as dependencies and fix issues with type checking against pandas stubs.
> Fix typechecking with pandas stubs

- docs/examples/Valon_5015.ipynb
- qcodes_contrib_drivers/drivers/Valon/Valon_5015.py
This PR: 
- Adds the `drivers/Valon/Valon_1505.py` file which contains the driver for the [Valon 5015](https://www.valonrf.com/5015-frequency-synthesizer-15ghz.html) Frequency Synthesizer instrument.
- Adds the `docs/examples/Valon_1505.ipynb` file which contains an example on how to use the driver.
Tests and sims are not implemented, but the driver has been tested manually in the lab.
> Drivers for Valon 5015 Frequency Synthesizer instrument

- docs/examples/QDevil/QDAC2/Sweep.ipynb
- qcodes_contrib_drivers/drivers/QDevil/QDAC2.py
- Sweep_Context now has a _set_generator_mode instead of the wrongly named _set_trigger_mode.
- Snapshots no longer complains about external triggers.
> QDAC2: Sweep generator and snapshot bugfixes

- README.rst
- docs/conf.py
- qcodes_contrib_drivers/drivers/Rigol/Rigol_DSG3136B.py
QCoDeS have moved to the Microsoft github org
> fix links to qcodes docs

- src/qcodes_contrib_drivers/drivers/Tektronix/Keithley_6430.py
Hi!
We noticed a bug in this SMU driver: writing an SCPI command to set a voltage compliance value that is below the minimum accepted by the device (0.2 mV) will cause the value to be silently ignored, and the previous compliance level will stay. Without this modification, it is possible to set the compliance to 0.1 mV in QCoDeS but accidentally pass 20 V, since that is the default voltage compliance when the device is booted. This PR fixes this behavior.
> Keithley 6430: Add appropriate lower limit for voltage compliance

- src/qcodes_contrib_drivers/drivers/StanfordResearchSystems/SR570.py
- based on existing QCoDeS (virtual) driver for SR560 voltage amplifier, but it actually talks to the instrument
- this driver could not be tested automatically because the device is not designed to respond
- all the functionality has been tested out manually by inspecting the output leds of the instrument
> Driver for Stanford SR570 Current Amplifier

- src/qcodes_contrib_drivers/drivers/Minicircuits/ZTM.py
Our system was recently equipped with Minicircuits modular test system (https://www.minicircuits.com/WebStore/ztm.html).
I created a new driver for the instrument, which reads out the modules installed in the system and makes an Instrument object with several InstrumentModules.
The driver was inspected by Mini-Circuits, but not reviewed.
The driver only includes the switch and amplifier modules, which are not of all available modules for the instruments. However, our device has only some of the possible modules, so I limited the driver to ones I could have tested explicitly, and the ones that are extremely similar.
> Mini circuits modular test system

- pyproject.toml
This used to be an transitive dependency of qcodes but that changed when qcodes dropped opencensus install
> add missing dependency on cffi for Advantech driver

- src/qcodes_contrib_drivers/drivers/Horiba/Horiba_FHR.py
To prepare for support of https://github.com/microsoft/Qcodes/pull/6012 where these args become kwargs only.
> pass metadata/label as kwarg

- src/qcodes_contrib_drivers/drivers/HP/HP8594E.py
should fix CI build
from the numpy changelog
> Alias np.float_ has been removed. Use np.float64 instead.
> Fix use of numpy 2 removed type

- src/qcodes_contrib_drivers/drivers/BlueFors/BlueFors.py
- src/qcodes_contrib_drivers/drivers/ERAInstruments/erasynth.py
- src/qcodes_contrib_drivers/drivers/OxfordInstruments/ILM200.py
- src/qcodes_contrib_drivers/drivers/QuTech/IVVI.py
- src/qcodes_contrib_drivers/drivers/Spectrum/M4i.py
- src/qcodes_contrib_drivers/drivers/StanfordResearchSystems/SIM928.py
- src/qcodes_contrib_drivers/drivers/ZurichInstruments/ZIHDAWG8.py
Including soon to be deprecated instrument.get/set from QCoDeS see https://github.com/microsoft/Qcodes/pull/6086
> Update to remove use of deprecated constructs

- src/qcodes_contrib_drivers/drivers/Tektronix/FCA3100.py
Dear qcodes people,
I hope to have done the git things correctly this time.
This pull request simply add two parameters to control the slope threshold.
Thanks.
Étienne.
> add slope threshold parameter

- docs/examples/Cryomagnetics/LM_500.ipynb
- src/qcodes_contrib_drivers/drivers/Cryomagnetics/LM_500.py
@astafan8 and @jenshnielsen could you please have a look.
> add cryomagnetics driver and examples LM500 helium level meter

- src/qcodes_contrib_drivers/drivers/Valon/Valon_5015.py
Also:
- Improve regex to take negative numbers when necessary
- For multiline telnet message, write once and read all lines, instead of asking multiple times and filling the buffer
- Fix typo in _set_modulation_frequency
Thanks to Colin Dietrich for help with these changes
This addresses the error in #393 for a Valon 5015, however I don't have a Valon 5019 to test with.
I think that this improves on PR #338 (the part modifying the Valon), which has a change which successfully clears the error, however it does not clear the IO buffers correctly, so if you were to successively run the `Valon5015.status` and `Valon5015.id` get commands, you would see the wrong output.
Tested on a Valon 5015 running FW 2.0a which is the latest at time of writing …
> Valon: Fix VI_ERROR_INV_MASK bug when flushing buffer

- .github/workflows/pytest.yaml
Codecov no longer takes a file argument but
discovers the files to upload from the current directory.
> Fix warning from codecov
